### ISSUE TITLE
Cmake - make fails after a clean

### ISSUE THREAD

**Issue by biwiki** [aregtech/areg-sdk#372]
**Describe the bug**
Using cmake, make command fails after clean previous build with `make clean`

**To Reproduce**
Steps to reproduce the behavior.
- `cmake -B build/`
- `cd build`
-  `make clean`
- `make -j 8`

**Expected behavior**
Build should succeed

**Screenshots**
NA

**Desktop or embedded (please complete the following information):**
- OS: Ubuntu
- Version 22.04
- Hardware x86
- Compiler [g++
- AREG SDK version: master
 
**Additional context**
```
/usr/bin/ld: cannot open output file ../product/build/gnu-c++/linux-64-x86_64-release-shared/bin/libareg.so: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/areg.dir/build.make:3057: ../product/build/gnu-c++/linux-64-x86_64-release-shared/bin/libareg.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:289: CMakeFiles/areg.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```
This is probably because the `bin` directory has been removed with `make clean`

**Comment by aregtech** [comment]
@biwiki , thank you for bug report.
Yes, this is because `linux-64-x86_64-release-shared` with subdirectories is removed. Technically, the solution should be restoring the directories. I need to think about the solution. It is not only creating directories `linux-64-x86_64-release-shared/bin` and `linux-64-x86_64-release-shared/lib`, but also copying files like `areg.init`. See the `CMakeLists.txt` in the `framework`

```cmake
# copying log and router init files to 'bin/config'
file(MAKE_DIRECTORY ${AREG_OUTPUT_BIN}/config)
file(COPY ${AREG_BASE}/areg/resources/areg.init DESTINATION ${AREG_OUTPUT_BIN}/config)

if("${AREG_DEVELOP_ENV}" STREQUAL "Win32")
    file(COPY ${mcrouter_RESOURCE}/mcrouter_install.bat DESTINATION ${AREG_OUTPUT_BIN}/)
    file(COPY ${mcrouter_RESOURCE}/mcrouter_uninstall.bat DESTINATION ${AREG_OUTPUT_BIN}/)
    file(COPY ${logger_RESOURCE}/logger_install.bat DESTINATION ${AREG_OUTPUT_BIN}/)
    file(COPY ${logger_RESOURCE}/logger_uninstall.bat DESTINATION ${AREG_OUTPUT_BIN}/)
else()
    file(COPY ${mcrouter_RESOURCE}/mcrouter.service DESTINATION ${AREG_OUTPUT_BIN}/)
    file(COPY ${logger_RESOURCE}/logger.service DESTINATION ${AREG_OUTPUT_BIN}/)
endif()
```

**Comment by aregtech** [comment]
I think, I found the rook cause. In the `common.cmake` file there is a script like this:
```cmake
# Adding areg/product directory for clean-up
set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_CLEAN_FILES ${AREG_OUTPUT_DIR})
```
The `AREG_OUTPUT_DIR` is `product/build/gnu-c++/linux-64-x86_64-release-shared`. That's why, when call `clean` it deletes the directory with all content. 

I added this script, thinking that it is easier to remove all. Now need to think either to remove this script or find the way to recreate the structure during build.

**Comment by biwiki** [comment]
Yes, I came across `common.cmake` and found that too. I think it would be more clean to create `bin` directory during the compilation, not at `cmake` command

**Comment by aregtech** [comment]
@biwiki , I've fixed the bug. Please check and review PR #373
