### ISSUE TITLE
Question: potential bug while testing AREG_BUILD_TESTS

### ISSUE THREAD

**Issue by biwiki** [aregtech/areg-sdk#466]
Hi @aregtech

I am not familiar with cmake, but there seems to be a bug in `conf/cmake/setup.cmake` while testing AREG_BUILD_TESTS

```
if (NOT AREG_BUILD_TESTS)
    set(AREG_GTEST_PACKAGE OFF)
endif()
```

Although, I could't find any information in the main README how to build/run/disable unittest

BR /biwiki

**Comment by aregtech** [comment]
Hi @biwiki,

It is not a bug. It says that if "build of unit tests are disabled, to not use GTest package". It plays no real role, simply set it, because at the end of configuration it types a report. Previously, it unit tests were disabled, it was typing "Unit tests == OFF, use GTest package == ON", which I found a little confusing.

Regarding disabling building Unit Tests, actually, there is a documentation [CMake Configuration Options for Building AREG SDK](https://github.com/aregtech/areg-sdk/blob/master/docs/wiki/02a-cmake-config.md#8-areg_build_tests). But you are right, such simple things like "disable unit tests" or "disable examples" are simple and they should be clearly described. Thank you for the note, I'll keep in mind and update documents.

To keep simple,
1. **Disable unit test build**:
   ```bash
   cmake -B ./build -DAREG_BUILD_TESTS=OFF
   ```
2. **Disable examples**:
   ```bash
   cmake -B ./build -DAREG_BUILD_EXAMPLES=OFF
   ```

**Comment by aregtech** [comment]
I keep this ticket opened to update documents.

**Comment by biwiki** [comment]
Thamks @aregtech , that would be so helpful!

**Comment by aregtech** [comment]
@biwiki , I appreciate very much if you report uncomfortable / confusing codes or descriptions.
I like your notes. They are reasonable.

**Comment by biwiki** [comment]
Thanks @aregtech .
Basically I knew how to build and run the tests, but it is a bit more convenience to have instructions on the main README since I have seen that quite often in other repos.

**Comment by aregtech** [comment]
@biwiki, this is what I mean. You notice the details I might miss. Even the most experienced developers can overlook certain use cases, which might lead to bugs -- it’s just part of the process. Your experience with frameworks and repositories really adds value here, and your feedback is helpful. My goal is to make this framework as useful and user-friendly as possible, so your insights are truly appreciated 🤝

**Comment by biwiki** [comment]
Thanks again for your kind words :+1: 
I am now curious to see our official instructions to run the test case, especially to run the test with different GTest options.
I.e, to run the test manually with a filter, I can do something like:
```
$ product/build/gnu-c++/linux-64-x86_64-release-shared/bin/areg-unit-tests.elf --gtest_filter=*DateTimeTest*
Running main() from /home/biwiki/git/areg-sdk/build/packages/googletest-src/googletest/src/gtest_main.cc
Note: Google Test filter = *DateTimeTest*
[==========] Running 4 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 4 tests from DateTimeTest
[ RUN      ] DateTimeTest.TestNow
[       OK ] DateTimeTest.TestNow (0 ms)
[ RUN      ] DateTimeTest.TestLocalTimeWin32
[       OK ] DateTimeTest.TestLocalTimeWin32 (0 ms)
[ RUN      ] DateTimeTest.TestLocalTime
[       OK ] DateTimeTest.TestLocalTime (0 ms)
[ RUN      ] DateTimeTest.TestFormatISO8601
[       OK ] DateTimeTest.TestFormatISO8601 (0 ms)
[----------] 4 tests from DateTimeTest (0 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test suite ran. (0 ms total)
[  PASSED  ] 4 tests.
```
These can be very useful for devs while working with the source base.

**Comment by aregtech** [comment]
Good point, this can be added in the [HOWTO.md](https://github.com/aregtech/areg-sdk/blob/master/docs/HOWTO.md) document. Or do you think i should create a separate document like "Tests and examples"?

**Comment by biwiki** [comment]
To me, it should be in a separate doco but I am not sure if that would be the best
